Add logic to commit `master` docker tag on master runs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,14 +1,16 @@
 name: Build and Test
 
 on:
+  pull_request:
+    paths-ignore:
+      - "**.md"
   push:
     branches:
+      - master
       - release/**
-  pull_request:
-    types:
-      - opened
-      - synchronize
-      - reopened
+    paths-ignore:
+      - "**.md"
+
 
 env:
   # Variables defined in the repository
@@ -38,16 +40,34 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Extract docker tag from action.yml
+      - name: Set git user to getsentry-bot
+        if: github.ref == 'refs/heads/master'
         run: |
-          TAG=$(yq '... | select(has("uses") and .uses | test("docker://ghcr.io/getsentry/action-release-image:.*")) | .uses' action.yml | awk -F':' '{print $3}')
-          echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV
-          
-          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-            if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-              echo "Error: DOCKER_TAG $TAG matching format MAJOR.MINOR.PATCH is not allowed inside pull requests."
-              echo "Please rename the docker tag in action.yml and try again."
-              exit 1
+          echo "GIT_COMMITTER_NAME=getsentry-bot" >> $GITHUB_ENV;
+          echo "GIT_AUTHOR_NAME=getsentry-bot" >> $GITHUB_ENV;
+          echo "EMAIL=bot@sentry.io" >> $GITHUB_ENV;
+
+      - name: Evaluate docker tag
+        run: |
+          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
+            echo "DOCKER_TAG=master" >> $GITHUB_ENV
+            yarn set-docker-tag master
+         
+            if ! git diff --quiet action.yml; then
+              git add action.yml
+              git commit -m "chore: Set docker tag for master [skip-ci]"
+              git push
+            fi
+          else
+            TAG=$(yq '... | select(has("uses") and .uses | test("docker://ghcr.io/getsentry/action-release-image:.*")) | .uses' action.yml | awk -F':' '{print $3}')
+            echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV
+            
+            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+              if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                echo "Error: DOCKER_TAG $TAG matching format MAJOR.MINOR.PATCH is not allowed inside pull requests."
+                echo "Please rename the docker tag in action.yml and try again."
+                exit 1
+              fi
             fi
           fi
 
